#!/bin/sh
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ $# -eq 1 ]; then
    TAG=$1
else
    TAG=${TAG:-${VERSION}}
fi

docker build -t filbox-backend:${TAG} .
echo build filbox-backend:${TAG}

docker tag filbox-backend:${TAG} harbor.raginghot.com.cn/szxjyt/filbox-backend:${TAG}
docker push harbor.raginghot.com.cn/szxjyt/filbox-backend:${TAG}
